package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.Item;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 03 10:33:55 CST 2020
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 03 10:33:55 CST 2020
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 03 10:33:55 CST 2020
     */
    Item selectByPrimaryKey(Integer id);
    List<Item> listItem();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 03 10:33:55 CST 2020
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Dec 03 10:33:55 CST 2020
     */
    int updateByPrimaryKey(Item record);

    void increaseSales(@Param("id") Integer id, @Param("amount")Integer amount);
}